version: '3'
services:
  db:
    image: mongo
    container_name: matrix-mongo
    environment:
      MONGO_INITDB_DATABASE: api-db
    ports:
      - "27017:27017"
  app:
    build: .
    container_name: api-container
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/api-db